sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.21.1
  # new
  DOCKER_COMPOSE_VERSION: 1.18.0
  COMMIT: ${TRAVIS_COMMIT::8}
  MAIN_REPO: https://github.com/testdrivenio/testdriven-app-2.2.git
  USERS: test-driven-users
  USERS_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/users
  USERS_DB: test-driven-users_db
  USERS_DB_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/users/project/db
  CLIENT: test-driven-client
  CLIENT_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/client
  SWAGGER: test-driven-swagger
  SWAGGER_REPO: ${MAIN_REPO}#${TRAVIS_BRANCH}:services/swagger

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
  - npm install

script:
  - bash test.sh stage

# new
after_success:
  - bash ./docker-push.sh
